### ISSUE TITLE
Put 128MB as max memory size in the functions yml

### ISSUE THREAD

**Issue by malaquiasdev** [malaquiasdev/studio-ghibli-api#3]
**Is your feature request related to a problem? Please describe.**
We don't have a `memorySize` property in our function yml, because of that the AWS is using as default value 1024MB, this is a lot of memory to our case and the cost to maintain is more high.

**Describe the solution you'd like**
We need change the function.yml of short_contents functions. With a new memory size.

To our case 128MB is great because the short_contents functions is not use more them 110MB.

```
 hello:
    handler: handler.hello # required, handler set in AWS Lambda
    name: ${self:provider.stage}-lambdaName # optional, Deployed Lambda name
    description: Description of what the lambda function does # optional, Description to publish to AWS
    runtime: python2.7 # optional overwrite, default is provider runtime
    memorySize: 512 # optional, in MB, default is 1024
    timeout: 10 # optional, in seconds, default is 6
    provisionedConcurrency: 3 # optional, Count of provisioned lambda instances
    reservedConcurrency: 5 # optional, reserved concurrency limit for this function. By default, AWS uses account concurrency limit
    tracing: PassThrough # optional, overwrite, can be 'Active' or 'PassThrough'
```

**Describe alternatives you've considered**

**Additional context**
Serverless Framework: AWS - Functions

https://serverless.com/framework/docs/providers/aws/guide/functions/
